FROM mhart/alpine-node:8

ARG env

RUN sed -i -e 's/dl-cdn/dl-4/g' /etc/apk/repositories

RUN apk update
RUN apk add git
WORKDIR /enterprise

COPY ./ /enterprise/

RUN npm config set registry https://registry.npm.taobao.org
RUN npm install -g pm2
RUN npm install

EXPOSE 3000

CMD ["/bin/bash"]
